---
- debug: var=OS_SERVERS

- name: run openstack cli to unshelve servers in env if any
  command: "openstack server unshelve {{ item }}"
  loop: "{{ groups[ENV_NAME] }}"
  when: 'ENV_NAME in groups'
  ignore_errors: yes

- name: include tasks in servers_expand.yml
  include_tasks: servers_expand.yml

- name: include tasks in servers_create.yml
  include_tasks: servers_create.yml
  when: _OS_SERVERS is defined and _OS_SERVERS|length > 0
